version: '3.8'
services:
  flask-container:
    build: ./flask
    container_name: flask-container
    networks:
      postgresql-container:
        ipv4_address: 127.0.0.1
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - 8080:8080
    depends_on:
      - postgresql-container
  postgresql-container:
    image: postgres:14
    container_name: postgresql-container
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
    # volumes:
    #   - postgresql_vol: /var/lib/postgresql/data

# volumes:
#   postgresql_vol: /var/lib/postgresql/data